ServerName localhost

<VirtualHost *:80>
    DocumentRoot "/usr/local/apache2/htdocs"

    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    # FastDL should serve static files directly without sendfile caching issues
    EnableSendfile Off
</VirtualHost>
